demo:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DEMO_ACCOUNT') }}"

      # User/password auth
      user: "{{ env_var('DEMO_USER') }}"
      password: "{{ env_var('DEMO_PASSWORD') }}"

      role: ACCOUNTADMIN
      database: demo
      warehouse: COMPUTE_WH
      schema: analytics
      threads: 1
